version: '3'
services:
    pia:
        image: qmcgaw/private-internet-access
        container_name: pia
        cap_add:
            - NET_ADMIN
        networks:
            - pianet
        volumes:
            - /yourpath/auth.conf:/auth.conf:ro
        environment:
            - PROTOCOL=tcp
            - ENCRYPTION=strong
            - REGION=Germany
        restart: always
        
networks:
    pianet:
        external: true