version: "3.7"
services:
  gluetun:
    image: qmcgaw/private-internet-access
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
    # command:
    volumes:
      - /yourpath:/gluetun
    environment:
      # More variables are available, see the readme table
      - VPNSP=private internet access

      # Timezone for accurate logs times
      - TZ=

      # All VPN providers
      - OPENVPN_USER=js89ds7

      # All VPN providers but Mullvad
      - PASSWORD=8fd9s239G

      # Cyberghost only
      - CLIENT_KEY=

      # All VPN providers but Mullvad
      - REGION=Austria

      # Mullvad only
      - COUNTRY=Sweden
    restart: always
