version: "3.7"

services:
  vscode:
    build: .
    image: godevcontainer
    volumes:
      - ../:/workspace
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory
      - ~/.ssh:/home/vscode/.ssh
      - ~/.ssh:/root/.ssh
      # Git config
      - ~/.gitconfig:/home/districter/.gitconfig
      - ~/.gitconfig:/root/.gitconfig
    environment:
      - TZ=
    cap_add:
      # For debugging with dlv
      - SYS_PTRACE
    security_opt:
      # For debugging with dlv
      - seccomp:unconfined
    entrypoint: zsh -c "while sleep 1000; do :; done"
